name: css-ccx-pkg-publish
on:
  push:
    paths:
      - package-css-ccx-publish.json
jobs:
  npm-packages-publish:
    name: npm-packages-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Prepare files for @adobe/spectrum-css-ccx-workflow-icons package
      run: cp package-css-ccx-publish.json ./dist/spectrum-css-ccx-workflow-icons/package.json && cp COPYRIGHT CODE_OF_CONDUCT.md LICENSE README.md dist/spectrum-css-ccx-workflow-icons/
    - name: Publish @adobe/spectrum-css-ccx-workflow-icons package
      working-directory: ./dist/spectrum-css-ccx-workflow-icons/
      run: npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
