name: npm-publish
on:
  push:
    branches:
      - main
jobs:
  npm-packages-publish:
    name: npm-packages-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Prepare files for @adobe/spectrum-css-workflow-icons package
      run: cp package-css-publish.json ./dist/spectrum-css-workflow-icons/package.json && cp COPYRIGHT CODE_OF_CONDUCT.md LICENSE README.md dist/spectrum-css-workflow-icons/
    - name: Publish @adobe/spectrum-css-workflow-icons package
      working-directory: ./dist/spectrum-css-workflow-icons/
      run: npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
    - name: Prepare files for @adobe/react-spectrum-workflow package
      run: cp package-css-publish.json ./dist/react-spectrum-workflow/package.json && cp LICENSE_rsp dist/react-spectrum-workflow/LICENSE
    - name: Publish @adobe/react-spectrum-workflow package
      working-directory: ./dist/react-spectrum-workflow/
      run: npm publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
